### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by grantv9** [TylerLubeck/HalliganHelper#79]
Date Found: Last semester

Browser Version (Please note that we do not currently support IE): All

Description of Bug: The SSL cert for Halliganhelper.com has expired.

Steps to Reproduce: Got to halliganhelper.com

CC @HalliganHelper/hh-core

**Comment by TylerLubeck** [comment]
Hey @grantv I'm sorry but this project hasn't been maintained in ages

**Comment by grantv9** [comment]
No problem but thanks for responding! Do you by any chance know who still owns the domain? The department still uses the site for COMP 40 TAing.

**Comment by TylerLubeck** [comment]
Hey @grantv9, I just bumped the cert. If you and your professor could please reach out to me from your tufts email addresses I'd like to talk again about actually handing support of this site over to you all, or shutting it down fully at the end of this semester.
